/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPricingResponse {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::ApiPricingModel>>,
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    /// UnpricedCount is the same fact as the per-model flag, totalled, so a dashboard or a CLI can alert without walking the list.
    #[serde(rename = "unpriced_count", skip_serializing_if = "Option::is_none")]
    pub unpriced_count: Option<i32>,
}

impl ApiPricingResponse {
    pub fn new() -> ApiPricingResponse {
        ApiPricingResponse {
            data: None,
            object: None,
            unit: None,
            unpriced_count: None,
        }
    }
}

