/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiPricingModel {
    #[serde(rename = "hosting", skip_serializing_if = "Option::is_none")]
    pub hosting: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "interface", skip_serializing_if = "Option::is_none")]
    pub interface: Option<String>,
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// Rates is micros per 1000 tokens, keyed by kind (input, output, cache_read, cache_write_5m, cache_write_1h). A kind ABSENT from this map has no rate on file; it is not zero. The distinction is the point of the endpoint — see Unpriced.
    #[serde(rename = "rates", skip_serializing_if = "Option::is_none")]
    pub rates: Option<std::collections::HashMap<String, i64>>,
    /// Unpriced reports that this model is callable and has NO input rate.  THIS IS THE FIELD THE ENDPOINT EXISTS FOR. A missing rate resolves to zero in the router's cost ranking, so an unpriced model reads as FREE and `auto` prefers it over every real supplier. Until now the only symptom was traffic silently moving. Reporting it as a boolean rather than as a zero in Rates keeps \"costs nothing\" and \"nobody set a price\" distinguishable, which is exactly the conflation that makes the defect invisible.  proven-by: TestPricing_AnUnpricedModelIsFlagged_NotReportedAsFree
    #[serde(rename = "unpriced", skip_serializing_if = "Option::is_none")]
    pub unpriced: Option<bool>,
}

impl ApiPricingModel {
    pub fn new() -> ApiPricingModel {
        ApiPricingModel {
            hosting: None,
            id: None,
            interface: None,
            provider: None,
            rates: None,
            unpriced: None,
        }
    }
}

