/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiUsageResponse {
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::StoreUsageRow>>,
    #[serde(rename = "since", skip_serializing_if = "Option::is_none")]
    pub since: Option<String>,
}

impl ApiUsageResponse {
    pub fn new() -> ApiUsageResponse {
        ApiUsageResponse {
            rows: None,
            since: None,
        }
    }
}

