/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiLeartechCache {
    #[serde(rename = "write_1h_tokens", skip_serializing_if = "Option::is_none")]
    pub write_1h_tokens: Option<i32>,
    #[serde(rename = "write_5m_tokens", skip_serializing_if = "Option::is_none")]
    pub write_5m_tokens: Option<i32>,
}

impl ApiLeartechCache {
    pub fn new() -> ApiLeartechCache {
        ApiLeartechCache {
            write_1h_tokens: None,
            write_5m_tokens: None,
        }
    }
}

