/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiProtectedResourceMetadata {
    /// Audience is a DEVIATION and is named as one. RFC 9728 expects a client to pass `resource` (RFC 8707) and receive a correctly-audienced token. This estate issues tokens carrying a bare audience string instead (LEARTECH_AUTH_AUDIENCE, \"leartech-ai-gateway\"), and the verifier enforces that value. A client that knew only `resource` would request the wrong thing and be refused, so the value it actually needs is published rather than left to be guessed from a 401.
    #[serde(rename = "audience", skip_serializing_if = "Option::is_none")]
    pub audience: Option<String>,
    /// AuthorizationServers is where to get a token. One entry: a gateway answers to exactly one issuer, and LEARTECH_AUTH_ISSUER is the same value the verifier enforces, so this does not drift from what is accepted.  proven-by: TestProtectedResource_PublishesWhatTheVerifierEnforces
    #[serde(rename = "authorization_servers", skip_serializing_if = "Option::is_none")]
    pub authorization_servers: Option<Vec<String>>,
    /// BearerMethodsSupported: the gateway takes a bearer header, and virtual keys additionally arrive via x-api-key. Only the standard method is listed, because this document describes the OAUTH resource and a virtual key is not an OAuth credential.
    #[serde(rename = "bearer_methods_supported", skip_serializing_if = "Option::is_none")]
    pub bearer_methods_supported: Option<Vec<String>>,
    /// Resource identifies this deployment. Derived from the request rather than configured, because the gateway is reached on a different host per cluster and nothing tells it which -- there is no PUBLIC_URL, and adding one would be a second source for a fact the request already carries.
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<String>,
    /// ScopesSupported is the published registry, not a hand-written list -- so a scope added to internal/authz appears here without anyone remembering to update a document.
    #[serde(rename = "scopes_supported", skip_serializing_if = "Option::is_none")]
    pub scopes_supported: Option<Vec<String>>,
}

impl ApiProtectedResourceMetadata {
    pub fn new() -> ApiProtectedResourceMetadata {
        ApiProtectedResourceMetadata {
            audience: None,
            authorization_servers: None,
            bearer_methods_supported: None,
            resource: None,
            scopes_supported: None,
        }
    }
}

