/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiCreateKeyRequest {
    #[serde(rename = "budget_micros")]
    pub budget_micros: i32,
    #[serde(rename = "expires_at", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<String>,
    #[serde(rename = "model_allowlist", skip_serializing_if = "Option::is_none")]
    pub model_allowlist: Option<Vec<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "rate_limit_rpm", skip_serializing_if = "Option::is_none")]
    pub rate_limit_rpm: Option<i32>,
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
}

impl ApiCreateKeyRequest {
    pub fn new(budget_micros: i32, name: String) -> ApiCreateKeyRequest {
        ApiCreateKeyRequest {
            budget_micros,
            expires_at: None,
            model_allowlist: None,
            name,
            rate_limit_rpm: None,
            scopes: None,
        }
    }
}

