/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiToolFunction {
    /// Description is what the model chooses on AND what a user reads at approval time, so it is written for both.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Parameters is a JSON Schema, kept RAW for the same reason ToolCall.Arguments is: the gateway publishes it without interpreting it, so a schema keyword we do not model survives translation.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl ApiToolFunction {
    pub fn new() -> ApiToolFunction {
        ApiToolFunction {
            description: None,
            name: None,
            parameters: None,
        }
    }
}

