/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiChatCompletionRequest {
    #[serde(rename = "max_tokens", skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    #[serde(rename = "messages")]
    pub messages: Vec<models::ApiChatMessage>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(rename = "x_leartech", skip_serializing_if = "Option::is_none")]
    pub x_leartech: Option<Box<models::ApiLeartechExt>>,
}

impl ApiChatCompletionRequest {
    pub fn new(messages: Vec<models::ApiChatMessage>, model: String) -> ApiChatCompletionRequest {
        ApiChatCompletionRequest {
            max_tokens: None,
            messages,
            model,
            stream: None,
            temperature: None,
            x_leartech: None,
        }
    }
}

