/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiStreamOptions {
    #[serde(rename = "include_usage", skip_serializing_if = "Option::is_none")]
    pub include_usage: Option<bool>,
}

impl ApiStreamOptions {
    pub fn new() -> ApiStreamOptions {
        ApiStreamOptions {
            include_usage: None,
        }
    }
}

