/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiTool {
    /// Available reports whether THIS credential may call it. Unavailable tools are still listed, deliberately: a shortened list makes \"why can this shell not search\" unanswerable without reading scopes by hand.  The client shows the full list and offers only the available ones to the model, so display and capability stay different lists. Offering an unavailable tool would have the model plan around a capability it does not have and then 403.
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<bool>,
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<Box<models::ApiToolFunction>>,
    /// Scope names what a caller would need, so \"unavailable\" is actionable rather than just a closed door.
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl ApiTool {
    pub fn new() -> ApiTool {
        ApiTool {
            available: None,
            function: None,
            scope: None,
            r#type: None,
        }
    }
}

