/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiCreateKeyResponse {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<Box<models::ApiKeyView>>,
    #[serde(rename = "keyid", skip_serializing_if = "Option::is_none")]
    pub keyid: Option<String>,
    #[serde(rename = "secret", skip_serializing_if = "Option::is_none")]
    pub secret: Option<String>,
}

impl ApiCreateKeyResponse {
    pub fn new() -> ApiCreateKeyResponse {
        ApiCreateKeyResponse {
            key: None,
            keyid: None,
            secret: None,
        }
    }
}

