/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiUsage {
    #[serde(rename = "completion_tokens", skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<i32>,
    #[serde(rename = "leartech_cache", skip_serializing_if = "Option::is_none")]
    pub leartech_cache: Option<Box<models::ApiLeartechCache>>,
    #[serde(rename = "prompt_tokens", skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<i32>,
    /// ONE CONVENTION IN THIS OBJECT: every detail field below is a SUBSET of PromptTokens, which is every prompt token processed. Reads and writes are disjoint subsets — a prefix is either served from cache or written to it, not both in one request.  Subset rather than additive, and the reason is a client we did not write. A naive OpenAI client reads prompt_tokens, ignores every detail field and multiplies by the input rate: under subset that OVER-estimates, because the cached portion actually bills at a fraction; under additive it UNDER-estimates by two orders of magnitude, because the written tokens carry a premium and are invisible. Erring safe for the clients we control least follows the same principle as absence-resolving-to-the-input-rate.  It also keeps total_tokens honest: because PromptTokens is already the whole, total = prompt + completion is simultaneously OpenAI-pure and reconcilable against the cost on the same response. Under an additive extension those two are in conflict and something has to give.  proven-by: TestUsageResponse_IsLosslessAcrossTheConventionFlip proven-by: TestUsageResponse_TotalTokensStaysOpenAIPure
    #[serde(rename = "prompt_tokens_details", skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<Box<models::ApiPromptTokensDetails>>,
    #[serde(rename = "total_tokens", skip_serializing_if = "Option::is_none")]
    pub total_tokens: Option<i32>,
}

impl ApiUsage {
    pub fn new() -> ApiUsage {
        ApiUsage {
            completion_tokens: None,
            leartech_cache: None,
            prompt_tokens: None,
            prompt_tokens_details: None,
            total_tokens: None,
        }
    }
}

