/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiChatCompletionRequest {
    #[serde(rename = "max_tokens", skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    #[serde(rename = "messages")]
    pub messages: Vec<models::ApiRequestMessage>,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    /// StreamOptions.IncludeUsage asks for a final chunk carrying the token and cache breakdown, the same shape OpenAI emits and the same one openai.go already sends UPSTREAM and parses back.  The gateway received usage on every streamed call, billed with it, and dropped it before the client -- so a streamed turn was the least visible traffic on the system while being the highest volume an agent loop produces. Found by the CLI session building the first streaming consumer.
    #[serde(rename = "stream_options", skip_serializing_if = "Option::is_none")]
    pub stream_options: Option<Box<models::ApiStreamOptions>>,
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(rename = "tool_choice", skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<serde_json::Value>,
    /// S7b passthrough: forwarded verbatim to OpenAI-compatible providers.
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<serde_json::Value>,
    #[serde(rename = "x_leartech", skip_serializing_if = "Option::is_none")]
    pub x_leartech: Option<Box<models::ApiLeartechExt>>,
}

impl ApiChatCompletionRequest {
    pub fn new(messages: Vec<models::ApiRequestMessage>, model: String) -> ApiChatCompletionRequest {
        ApiChatCompletionRequest {
            max_tokens: None,
            messages,
            model,
            stream: None,
            stream_options: None,
            temperature: None,
            tool_choice: None,
            tools: None,
            x_leartech: None,
        }
    }
}

