/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiWebSearchProvider {
    /// Default is the provider used when a request omits `provider`.
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<bool>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// the `provider` value a request sends
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Keyless reports whether this provider runs with no third-party credential (searxng aggregates keyless engines) — the \"open lane\" vs the \"curated lane\" a caller may be choosing between.
    #[serde(rename = "keyless", skip_serializing_if = "Option::is_none")]
    pub keyless: Option<bool>,
    /// human-facing
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl ApiWebSearchProvider {
    pub fn new() -> ApiWebSearchProvider {
        ApiWebSearchProvider {
            default: None,
            description: None,
            id: None,
            keyless: None,
            name: None,
        }
    }
}

