/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiChatMessage {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
}

impl ApiChatMessage {
    pub fn new() -> ApiChatMessage {
        ApiChatMessage {
            content: None,
            role: None,
        }
    }
}

