/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiVersionResponse {
    #[serde(rename = "api_level", skip_serializing_if = "Option::is_none")]
    pub api_level: Option<i32>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl ApiVersionResponse {
    pub fn new() -> ApiVersionResponse {
        ApiVersionResponse {
            api_level: None,
            version: None,
        }
    }
}

