/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiLeartechExt {
    #[serde(rename = "require_residency", skip_serializing_if = "Option::is_none")]
    pub require_residency: Option<String>,
    #[serde(rename = "routing_hint", skip_serializing_if = "Option::is_none")]
    pub routing_hint: Option<String>,
    #[serde(rename = "trace_id", skip_serializing_if = "Option::is_none")]
    pub trace_id: Option<String>,
}

impl ApiLeartechExt {
    pub fn new() -> ApiLeartechExt {
        ApiLeartechExt {
            require_residency: None,
            routing_hint: None,
            trace_id: None,
        }
    }
}

