/*
 * leartech-ai-gateway
 *
 * OpenAI-compatible model gateway. Callers use logical model names; the gateway routes to the best-fit provider (native / LiteLLM / sidecar).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreUsageRow {
    #[serde(rename = "calls", skip_serializing_if = "Option::is_none")]
    pub calls: Option<i32>,
    #[serde(rename = "completion_tokens", skip_serializing_if = "Option::is_none")]
    pub completion_tokens: Option<i32>,
    #[serde(rename = "cost_micros", skip_serializing_if = "Option::is_none")]
    pub cost_micros: Option<i32>,
    #[serde(rename = "keyid", skip_serializing_if = "Option::is_none")]
    pub keyid: Option<String>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(rename = "prompt_tokens", skip_serializing_if = "Option::is_none")]
    pub prompt_tokens: Option<i32>,
}

impl StoreUsageRow {
    pub fn new() -> StoreUsageRow {
        StoreUsageRow {
            calls: None,
            completion_tokens: None,
            cost_micros: None,
            keyid: None,
            model: None,
            prompt_tokens: None,
        }
    }
}

