/*
 * Leartech Mortgages Gateway
 *
 * Mortgages-domain gateway — MCP (streamable HTTP at /mcp) + REST (at /api/v1/_*) front door. Currently hosts mock sourcing tools for the ChatGPT integration spike; real downstream calls to leartech-mortgages-api land in a subsequent initiative. Calls leartech-mortgages-api via generated Go SDK once that's wired.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersExampleResponse {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}

impl HandlersExampleResponse {
    pub fn new() -> HandlersExampleResponse {
        HandlersExampleResponse {
            message: None,
            service: None,
        }
    }
}

