/*
 * Leartech Mortgages Gateway
 *
 * Mortgages-domain gateway — MCP (streamable HTTP) + REST front door. Speaks Model Context Protocol at /mcp for Claude/ChatGPT, REST at /api/v1/_* for future SPA/mobile/partner clients. Calls leartech-mortgages-api via generated Go SDK. Auth/audit/rate-limit chokepoint for the mortgages domain.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersFleetTestResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::HandlersPeerResult>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

impl HandlersFleetTestResponse {
    pub fn new() -> HandlersFleetTestResponse {
        HandlersFleetTestResponse {
            results: None,
            success: None,
            summary: None,
        }
    }
}

