/*
 * Leartech Go Service Template API
 *
 * Golden Go service template — replace this description after cloning.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersBaPass {
    /// questions closed this pass (0 or 1 — one per pass)
    #[serde(rename = "answered", skip_serializing_if = "Option::is_none")]
    pub answered: Option<i32>,
    #[serde(rename = "at", skip_serializing_if = "Option::is_none")]
    pub at: Option<String>,
    /// the failure, verbatim, when the pass failed
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// R1 tripped; nothing picked up
    #[serde(rename = "exhausted", skip_serializing_if = "Option::is_none")]
    pub exhausted: Option<bool>,
    /// the finding PR, when one was filed
    #[serde(rename = "pr", skip_serializing_if = "Option::is_none")]
    pub pr: Option<String>,
}

impl HandlersBaPass {
    pub fn new() -> HandlersBaPass {
        HandlersBaPass {
            answered: None,
            at: None,
            error: None,
            exhausted: None,
            pr: None,
        }
    }
}

