/*
 * Leartech Go Service Template API
 *
 * Golden Go service template — replace this description after cloning.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersShellPrompt {
    /// Label is the human name for this prompt, if the cluster set one. Free text for a reader; Revision is what identifies it.
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    /// Prompt is the system prompt, or empty when this cluster sets none.
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    /// Revision identifies this exact text.  A content hash, not a hand-set number. // proven-by: TestShellPrompt_RevisionIsDerivedFromTheContent A version someone has to remember to bump goes stale quietly, and two different prompts claiming one revision make every session recorded against it unreadable. Derived from the bytes, so it agrees with what was served.  proven-by: TestShellPrompt_RevisionIsDerivedFromTheContent proven-by: TestShellPrompt_DifferentPromptsNeverShareARevision
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    /// Source names where the value came from, for a client that has to tell an operator which prompt it is running.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl HandlersShellPrompt {
    pub fn new() -> HandlersShellPrompt {
        HandlersShellPrompt {
            label: None,
            prompt: None,
            revision: None,
            source: None,
        }
    }
}

