/*
 * Leartech Go Service Template API
 *
 * Golden Go service template — replace this description after cloning.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersClientsResponse {
    #[serde(rename = "checksums_url", skip_serializing_if = "Option::is_none")]
    pub checksums_url: Option<String>,
    #[serde(rename = "clients", skip_serializing_if = "Option::is_none")]
    pub clients: Option<Vec<models::HandlersClientBinary>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
}

impl HandlersClientsResponse {
    pub fn new() -> HandlersClientsResponse {
        HandlersClientsResponse {
            checksums_url: None,
            clients: None,
            version: None,
        }
    }
}

