/*
 * leartech-rust-service-template
 *
 * Golden Rust HTTP service starter for leartech.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExampleResponse {
    /// Static demo message — replace with real service output.
    #[serde(rename = "message")]
    pub message: String,
    /// Echoes back the validated user-id from the bearer token.
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl ExampleResponse {
    pub fn new(message: String, user_id: String) -> ExampleResponse {
        ExampleResponse {
            message,
            user_id,
        }
    }
}

