/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait EventMaestroApi: Send + Sync {

    /// POST /api/event_maestro/announce_event
    ///
    /// Announces an event for a case to maestro
    async fn announce_event<'announce_request>(&self, announce_request: models::AnnounceEventRequest) -> Result<models::AnnounceEventResponse, Error<AnnounceEventError>>;

    /// POST /api/event_maestro/consume_event
    ///
    /// This is a place-holder for consistent package generation, and as an example of the consume endpoint
    async fn consume_event<'consume_request>(&self, consume_request: models::ConsumeEventRequest) -> Result<models::ConsumeEventResponse, Error<ConsumeEventError>>;

    /// GET /api/event_maestro/events_by_annotation/{annotation_key}/{annotation_value}
    ///
    /// Retrieves events by annotation
    async fn get_events_by_annotation<'annotation_key, 'annotation_value>(&self, annotation_key: &'annotation_key str, annotation_value: &'annotation_value str) -> Result<models::GetEventsDtoResponse, Error<GetEventsByAnnotationError>>;

    /// PUT /api/event_maestro/reprocess_event/{event_id}
    ///
    /// Reprocesses an event from the maestro events log, usually for failed events
    async fn reprocess_event<'event_id, 'only_failures>(&self, event_id: &'event_id str, only_failures: Option<bool>) -> Result<models::Response, Error<ReprocessEventError>>;

    /// PUT /api/event_maestro/reprocess_event_for_consumer/{event_id}/{consumer_name}
    ///
    /// Reprocesses an event for a specific consumer
    async fn reprocess_event_for_consumer<'event_id, 'consumer_name>(&self, event_id: &'event_id str, consumer_name: &'consumer_name str) -> Result<models::Response, Error<ReprocessEventForConsumerError>>;
}

pub struct EventMaestroApiClient {
    configuration: Arc<configuration::Configuration>
}

impl EventMaestroApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl EventMaestroApi for EventMaestroApiClient {
    /// Announces an event for a case to maestro
    async fn announce_event<'announce_request>(&self, announce_request: models::AnnounceEventRequest) -> Result<models::AnnounceEventResponse, Error<AnnounceEventError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/event_maestro/announce_event", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&announce_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AnnounceEventResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AnnounceEventResponse`")))),
            }
        } else {
            let local_var_entity: Option<AnnounceEventError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// This is a place-holder for consistent package generation, and as an example of the consume endpoint
    async fn consume_event<'consume_request>(&self, consume_request: models::ConsumeEventRequest) -> Result<models::ConsumeEventResponse, Error<ConsumeEventError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/event_maestro/consume_event", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&consume_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ConsumeEventResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ConsumeEventResponse`")))),
            }
        } else {
            let local_var_entity: Option<ConsumeEventError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Retrieves events by annotation
    async fn get_events_by_annotation<'annotation_key, 'annotation_value>(&self, annotation_key: &'annotation_key str, annotation_value: &'annotation_value str) -> Result<models::GetEventsDtoResponse, Error<GetEventsByAnnotationError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/event_maestro/events_by_annotation/{annotation_key}/{annotation_value}", local_var_configuration.base_path, annotation_key=crate::apis::urlencode(annotation_key), annotation_value=crate::apis::urlencode(annotation_value));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::GetEventsDtoResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GetEventsDtoResponse`")))),
            }
        } else {
            let local_var_entity: Option<GetEventsByAnnotationError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Reprocesses an event from the maestro events log, usually for failed events
    async fn reprocess_event<'event_id, 'only_failures>(&self, event_id: &'event_id str, only_failures: Option<bool>) -> Result<models::Response, Error<ReprocessEventError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/event_maestro/reprocess_event/{event_id}", local_var_configuration.base_path, event_id=crate::apis::urlencode(event_id));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref param_value) = only_failures {
            local_var_req_builder = local_var_req_builder.query(&[("only_failures", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Response`")))),
            }
        } else {
            let local_var_entity: Option<ReprocessEventError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Reprocesses an event for a specific consumer
    async fn reprocess_event_for_consumer<'event_id, 'consumer_name>(&self, event_id: &'event_id str, consumer_name: &'consumer_name str) -> Result<models::Response, Error<ReprocessEventForConsumerError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/event_maestro/reprocess_event_for_consumer/{event_id}/{consumer_name}", local_var_configuration.base_path, event_id=crate::apis::urlencode(event_id), consumer_name=crate::apis::urlencode(consumer_name));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Response`")))),
            }
        } else {
            let local_var_entity: Option<ReprocessEventForConsumerError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`EventMaestroApi::announce_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AnnounceEventError {
    Status400(models::Response),
    Status404(models::Response),
    Status500(models::Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`EventMaestroApi::consume_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ConsumeEventError {
    Status400(models::Response),
    Status404(models::Response),
    Status500(models::Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`EventMaestroApi::get_events_by_annotation`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetEventsByAnnotationError {
    Status400(models::Response),
    Status500(models::Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`EventMaestroApi::reprocess_event`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReprocessEventError {
    Status400(models::Response),
    Status404(models::Response),
    Status500(models::Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`EventMaestroApi::reprocess_event_for_consumer`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReprocessEventForConsumerError {
    Status400(models::Response),
    Status404(models::Response),
    Status500(models::Response),
    UnknownValue(serde_json::Value),
}

