/*
 * Leartech Blockchain API
 *
 * Blockchain API service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainTransaction {
    #[serde(rename = "hash", skip_serializing_if = "Option::is_none")]
    pub hash: Option<String>,
    #[serde(rename = "receipt", skip_serializing_if = "Option::is_none")]
    pub receipt: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl BlockchainTransaction {
    pub fn new() -> BlockchainTransaction {
        BlockchainTransaction {
            hash: None,
            receipt: None,
            status: None,
        }
    }
}

