/*
 * Leartech Blockchain API
 *
 * Blockchain API service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersReadContractRequest {
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<Vec<serde_json::Value>>,
    #[serde(rename = "method")]
    pub method: String,
}

impl HandlersReadContractRequest {
    pub fn new(method: String) -> HandlersReadContractRequest {
        HandlersReadContractRequest {
            args: None,
            method,
        }
    }
}

