/*
 * Leartech Blockchain API
 *
 * Blockchain API service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersListResponse {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<serde_json::Value>,
}

impl HandlersListResponse {
    pub fn new() -> HandlersListResponse {
        HandlersListResponse {
            items: None,
        }
    }
}

