/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnnounceEventRequest {
    /// Who actioned the event (userId if applicable - optional)
    #[serde(rename = "actionedBy", skip_serializing_if = "Option::is_none")]
    pub actioned_by: Option<String>,
    /// Annotations associated with the event
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    /// Name of the event to be announced
    #[serde(rename = "name")]
    pub name: String,
    /// Which service produced the event
    #[serde(rename = "producedBy")]
    pub produced_by: String,
}

impl AnnounceEventRequest {
    pub fn new(name: String, produced_by: String) -> AnnounceEventRequest {
        AnnounceEventRequest {
            actioned_by: None,
            annotations: None,
            name,
            produced_by,
        }
    }
}

