/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsumeEventResponse {
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    #[serde(rename = "isConsumed", skip_serializing_if = "Option::is_none")]
    pub is_consumed: Option<bool>,
    #[serde(rename = "isErrored", skip_serializing_if = "Option::is_none")]
    pub is_errored: Option<bool>,
}

impl ConsumeEventResponse {
    pub fn new() -> ConsumeEventResponse {
        ConsumeEventResponse {
            error_reason: None,
            is_consumed: None,
            is_errored: None,
        }
    }
}

