/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConsumeEventRequest {
    #[serde(rename = "actionedBy", skip_serializing_if = "Option::is_none")]
    pub actioned_by: Option<String>,
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "producedTime")]
    pub produced_time: String,
}

impl ConsumeEventRequest {
    pub fn new(id: String, name: String, produced_time: String) -> ConsumeEventRequest {
        ConsumeEventRequest {
            actioned_by: None,
            annotations: None,
            id,
            name,
            produced_time,
        }
    }
}

