/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Consumer {
    #[serde(rename = "serviceName", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl Consumer {
    pub fn new() -> Consumer {
        Consumer {
            service_name: None,
            url: None,
        }
    }
}

