/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventRegistrationInfo {
    #[serde(rename = "consumers", skip_serializing_if = "Option::is_none")]
    pub consumers: Option<Vec<models::Consumer>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "producer", skip_serializing_if = "Option::is_none")]
    pub producer: Option<Box<models::Producer>>,
}

impl EventRegistrationInfo {
    pub fn new() -> EventRegistrationInfo {
        EventRegistrationInfo {
            consumers: None,
            name: None,
            producer: None,
        }
    }
}

