/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventDto {
    #[serde(rename = "actionedBy", skip_serializing_if = "Option::is_none")]
    pub actioned_by: Option<String>,
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "consumptions", skip_serializing_if = "Option::is_none")]
    pub consumptions: Option<Vec<models::EventConsumptionDto>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "producedBy", skip_serializing_if = "Option::is_none")]
    pub produced_by: Option<String>,
    #[serde(rename = "producedTime", skip_serializing_if = "Option::is_none")]
    pub produced_time: Option<String>,
}

impl EventDto {
    pub fn new() -> EventDto {
        EventDto {
            actioned_by: None,
            annotations: None,
            consumptions: None,
            id: None,
            name: None,
            produced_by: None,
            produced_time: None,
        }
    }
}

