/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEventsDtoResponse {
    #[serde(rename = "errorDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_description: Option<Option<String>>,
    #[serde(rename = "events", skip_serializing_if = "Option::is_none")]
    pub events: Option<Vec<models::EventDto>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
}

impl GetEventsDtoResponse {
    pub fn new() -> GetEventsDtoResponse {
        GetEventsDtoResponse {
            error_description: None,
            events: None,
            success: None,
        }
    }
}

