/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestSuccessfulEventConsumptionDto {
    #[serde(rename = "consumedBy", skip_serializing_if = "Option::is_none")]
    pub consumed_by: Option<String>,
    #[serde(rename = "consumedTime", skip_serializing_if = "Option::is_none")]
    pub consumed_time: Option<String>,
}

impl LatestSuccessfulEventConsumptionDto {
    pub fn new() -> LatestSuccessfulEventConsumptionDto {
        LatestSuccessfulEventConsumptionDto {
            consumed_by: None,
            consumed_time: None,
        }
    }
}

