/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LatestEventDto {
    #[serde(rename = "latestFailedConsumptions", skip_serializing_if = "Option::is_none")]
    pub latest_failed_consumptions: Option<Vec<models::LatestFailedEventConsumptionDto>>,
    #[serde(rename = "latestSuccessfulConsumptions", skip_serializing_if = "Option::is_none")]
    pub latest_successful_consumptions: Option<Vec<models::LatestSuccessfulEventConsumptionDto>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "producedBy", skip_serializing_if = "Option::is_none")]
    pub produced_by: Option<String>,
    #[serde(rename = "producedTime", skip_serializing_if = "Option::is_none")]
    pub produced_time: Option<String>,
}

impl LatestEventDto {
    pub fn new() -> LatestEventDto {
        LatestEventDto {
            latest_failed_consumptions: None,
            latest_successful_consumptions: None,
            name: None,
            produced_by: None,
            produced_time: None,
        }
    }
}

