/*
 * Maestro Service API
 *
 * mini orchestration service for handling events
 *
 * The version of the OpenAPI document: 4.3.6-dev+b9e6bf9
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Producer {
    #[serde(rename = "annotationKeys", skip_serializing_if = "Option::is_none")]
    pub annotation_keys: Option<Vec<String>>,
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<String>,
    #[serde(rename = "serviceName", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
}

impl Producer {
    pub fn new() -> Producer {
        Producer {
            annotation_keys: None,
            queue: None,
            service_name: None,
        }
    }
}

