/*
 * Leartech Mortgages API
 *
 * Mortgages-domain BFF / orchestrator. REST + OpenAPI; sourcing comparison, indicative affordability, total-cost calculation, saved sourcing sessions, minimal case header. Consumed by leartech-mortgages-gw and any future SPA/mobile/partner client via auto-generated SDKs.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersExampleResponse {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
}

impl HandlersExampleResponse {
    pub fn new() -> HandlersExampleResponse {
        HandlersExampleResponse {
            message: None,
            service: None,
        }
    }
}

