/*
 * leartech-rust-service-template
 *
 * Golden Rust HTTP service starter for leartech.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait ExampleApi: Send + Sync {

    /// GET /api/v1/example
    ///
    /// The `Claims` extractor pulls the validated token claims out of request extensions where `AuthLayer` placed them. If the layer wasn't applied, the extractor returns 500 (operator misconfig — distinct from a client-side 401/403 the layer itself would have produced for invalid tokens).
    async fn example<>(&self, ) -> Result<models::ExampleResponse, Error<ExampleError>>;
}

pub struct ExampleApiClient {
    configuration: Arc<configuration::Configuration>
}

impl ExampleApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl ExampleApi for ExampleApiClient {
    /// The `Claims` extractor pulls the validated token claims out of request extensions where `AuthLayer` placed them. If the layer wasn't applied, the extractor returns 500 (operator misconfig — distinct from a client-side 401/403 the layer itself would have produced for invalid tokens).
    async fn example<>(&self, ) -> Result<models::ExampleResponse, Error<ExampleError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/example", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ExampleResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::ExampleResponse`")))),
            }
        } else {
            let local_var_entity: Option<ExampleError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`ExampleApi::example`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExampleError {
    Status401(),
    Status403(),
    UnknownValue(serde_json::Value),
}

