/*
 * Leartech Blockchain API
 *
 * Blockchain API service.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
#[cfg(feature = "mockall")]
use mockall::automock;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[cfg_attr(feature = "mockall", automock)]
#[async_trait]
pub trait BlockchainApi: Send + Sync {

    /// GET /api/v1/chain/status
    ///
    /// 
    async fn api_v1_chain_status_get<>(&self, ) -> Result<models::BlockchainChainStatus, Error<ApiV1ChainStatusGetError>>;

    /// POST /api/v1/contracts/{address}/read
    ///
    /// 
    async fn api_v1_contracts_address_read_post<'address, 'body>(&self, address: &'address str, body: models::HandlersReadContractRequest) -> Result<models::BlockchainReadResult, Error<ApiV1ContractsAddressReadPostError>>;

    /// GET /api/v1/contracts
    ///
    /// 
    async fn api_v1_contracts_get<'name, 'kind>(&self, name: Option<&'name str>, kind: Option<&'kind str>) -> Result<models::HandlersListResponse, Error<ApiV1ContractsGetError>>;

    /// GET /api/v1/deployments
    ///
    /// 
    async fn api_v1_deployments_get<'contract, 'chain, 'address>(&self, contract: Option<&'contract str>, chain: Option<&'chain str>, address: Option<&'address str>) -> Result<models::HandlersListResponse, Error<ApiV1DeploymentsGetError>>;

    /// GET /api/v1/events
    ///
    /// 
    async fn api_v1_events_get<'address, 'event, 'from_block, 'to_block, 'tx_hash>(&self, address: Option<&'address str>, event: Option<&'event str>, from_block: Option<i32>, to_block: Option<i32>, tx_hash: Option<&'tx_hash str>) -> Result<models::HandlersListResponse, Error<ApiV1EventsGetError>>;

    /// GET /api/v1/transactions/{hash}
    ///
    /// 
    async fn api_v1_transactions_hash_get<'hash>(&self, hash: &'hash str) -> Result<models::BlockchainTransaction, Error<ApiV1TransactionsHashGetError>>;
}

pub struct BlockchainApiClient {
    configuration: Arc<configuration::Configuration>
}

impl BlockchainApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}



#[async_trait]
impl BlockchainApi for BlockchainApiClient {
    async fn api_v1_chain_status_get<>(&self, ) -> Result<models::BlockchainChainStatus, Error<ApiV1ChainStatusGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/chain/status", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BlockchainChainStatus`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::BlockchainChainStatus`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1ChainStatusGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_contracts_address_read_post<'address, 'body>(&self, address: &'address str, body: models::HandlersReadContractRequest) -> Result<models::BlockchainReadResult, Error<ApiV1ContractsAddressReadPostError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/contracts/{address}/read", local_var_configuration.base_path, address=crate::apis::urlencode(address));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&body);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BlockchainReadResult`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::BlockchainReadResult`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1ContractsAddressReadPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_contracts_get<'name, 'kind>(&self, name: Option<&'name str>, kind: Option<&'kind str>) -> Result<models::HandlersListResponse, Error<ApiV1ContractsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/contracts", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = name {
            local_var_req_builder = local_var_req_builder.query(&[("name", &param_value.to_string())]);
        }
        if let Some(ref param_value) = kind {
            local_var_req_builder = local_var_req_builder.query(&[("kind", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::HandlersListResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HandlersListResponse`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1ContractsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_deployments_get<'contract, 'chain, 'address>(&self, contract: Option<&'contract str>, chain: Option<&'chain str>, address: Option<&'address str>) -> Result<models::HandlersListResponse, Error<ApiV1DeploymentsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/deployments", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = contract {
            local_var_req_builder = local_var_req_builder.query(&[("contract", &param_value.to_string())]);
        }
        if let Some(ref param_value) = chain {
            local_var_req_builder = local_var_req_builder.query(&[("chain", &param_value.to_string())]);
        }
        if let Some(ref param_value) = address {
            local_var_req_builder = local_var_req_builder.query(&[("address", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::HandlersListResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HandlersListResponse`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1DeploymentsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_events_get<'address, 'event, 'from_block, 'to_block, 'tx_hash>(&self, address: Option<&'address str>, event: Option<&'event str>, from_block: Option<i32>, to_block: Option<i32>, tx_hash: Option<&'tx_hash str>) -> Result<models::HandlersListResponse, Error<ApiV1EventsGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/events", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = address {
            local_var_req_builder = local_var_req_builder.query(&[("address", &param_value.to_string())]);
        }
        if let Some(ref param_value) = event {
            local_var_req_builder = local_var_req_builder.query(&[("event", &param_value.to_string())]);
        }
        if let Some(ref param_value) = from_block {
            local_var_req_builder = local_var_req_builder.query(&[("from_block", &param_value.to_string())]);
        }
        if let Some(ref param_value) = to_block {
            local_var_req_builder = local_var_req_builder.query(&[("to_block", &param_value.to_string())]);
        }
        if let Some(ref param_value) = tx_hash {
            local_var_req_builder = local_var_req_builder.query(&[("tx_hash", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::HandlersListResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::HandlersListResponse`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1EventsGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn api_v1_transactions_hash_get<'hash>(&self, hash: &'hash str) -> Result<models::BlockchainTransaction, Error<ApiV1TransactionsHashGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/v1/transactions/{hash}", local_var_configuration.base_path, hash=crate::apis::urlencode(hash));
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("Authorization", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::BlockchainTransaction`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::BlockchainTransaction`")))),
            }
        } else {
            let local_var_entity: Option<ApiV1TransactionsHashGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`BlockchainApi::api_v1_chain_status_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ChainStatusGetError {
    Status503(std::collections::HashMap<String, String>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BlockchainApi::api_v1_contracts_address_read_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ContractsAddressReadPostError {
    Status404(std::collections::HashMap<String, String>),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BlockchainApi::api_v1_contracts_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1ContractsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BlockchainApi::api_v1_deployments_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1DeploymentsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BlockchainApi::api_v1_events_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1EventsGetError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`BlockchainApi::api_v1_transactions_hash_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApiV1TransactionsHashGetError {
    Status404(std::collections::HashMap<String, String>),
    UnknownValue(serde_json::Value),
}

