/*
 * Leartech Plan Conformance Consumer API
 *
 * Reference Maestro CONSUMER service — accepts events on POST /consume_event, records them, exposes /confirmed + /events for test-runners to assert an event actually flowed end-to-end. Deployed into jx-plan-conformance and pointed at the isolated Maestro bus.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaestroConsumeEventResponse {
    /// ErrorReason is a human-readable description when IsErrored is true or when the event was dropped for a non-error reason (unknown event, malformed body).
    #[serde(rename = "errorReason", skip_serializing_if = "Option::is_none")]
    pub error_reason: Option<String>,
    /// IsConsumed is true when the event was successfully handled. Maestro treats IsConsumed=true (regardless of HTTP status) as \"settled, do not retry\".
    #[serde(rename = "isConsumed", skip_serializing_if = "Option::is_none")]
    pub is_consumed: Option<bool>,
    /// IsErrored is true when handler execution failed. Distinct from !IsConsumed so we can signal \"no handler registered\" (neither consumed nor errored) vs. \"handler ran and blew up\" (errored).
    #[serde(rename = "isErrored", skip_serializing_if = "Option::is_none")]
    pub is_errored: Option<bool>,
}

impl MaestroConsumeEventResponse {
    pub fn new() -> MaestroConsumeEventResponse {
        MaestroConsumeEventResponse {
            error_reason: None,
            is_consumed: None,
            is_errored: None,
        }
    }
}

