/*
 * Leartech Plan Conformance Consumer API
 *
 * Reference Maestro CONSUMER service — accepts events on POST /consume_event, records them, exposes /confirmed + /events for test-runners to assert an event actually flowed end-to-end. Deployed into jx-plan-conformance and pointed at the isolated Maestro bus.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaestroConsumeEventRequestDto {
    /// ActionedBy is the userId (or system-actor id) from the announcement, when present.
    #[serde(rename = "actionedBy", skip_serializing_if = "Option::is_none")]
    pub actioned_by: Option<String>,
    /// Annotations are the string k/v pairs from the announcement. Same vocabulary as pkg/maestro.Event.Annotations on the producer side.
    #[serde(rename = "annotations", skip_serializing_if = "Option::is_none")]
    pub annotations: Option<std::collections::HashMap<String, String>>,
    /// ID is the unique event id Maestro assigned at announce time.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Name is the dotted event name — the dispatch key.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ProducedTime is the RFC3339 timestamp of the original announcement. Maestro emits an RFC3339 string; we decode with time.Time so downstream handlers get a native value.
    #[serde(rename = "producedTime", skip_serializing_if = "Option::is_none")]
    pub produced_time: Option<String>,
}

impl MaestroConsumeEventRequestDto {
    pub fn new() -> MaestroConsumeEventRequestDto {
        MaestroConsumeEventRequestDto {
            actioned_by: None,
            annotations: None,
            id: None,
            name: None,
            produced_time: None,
        }
    }
}

