/*
 * Leartech Go Service Template API
 *
 * Golden Go service template — replace this description after cloning.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HandlersFleetTestResponse {
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<models::HandlersPeerResult>>,
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
}

impl HandlersFleetTestResponse {
    pub fn new() -> HandlersFleetTestResponse {
        HandlersFleetTestResponse {
            results: None,
            success: None,
            summary: None,
        }
    }
}

